config/routes.rb
Rails.application.routes.draw do
  resources :agenda_items
  devise_for :users
  resources :users
  resources :rooms

   root 'rooms#index'

    resources :meets

end

app/models/agenda_item.rb
class AgendaItem < ActiveRecord::Base
	belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
	validates_presence_of :title

	belongs_to :user
	has_many :agenda_items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rooms
end

app/controllers/agenda_items_controller.rb
class AgendaItemsController < ApplicationController
  before_action :set_agenda_item, only: [:show, :edit, :update, :destroy]

  # GET /agenda_items
  # GET /agenda_items.json
  def index
    @agenda_items = AgendaItem.all
  end

  # GET /agenda_items/1
  # GET /agenda_items/1.json
  def show
  end

  # GET /agenda_items/new
  def new
    @agenda_item = AgendaItem.new
  end

  # GET /agenda_items/1/edit
  def edit
  end

  # POST /agenda_items
  # POST /agenda_items.json
  def create
    @agenda_item = AgendaItem.new(agenda_item_params)

    respond_to do |format|
      if @agenda_item.save
        format.html { redirect_to @agenda_item, notice: 'Agenda item was successfully created.' }
        format.json { render :show, status: :created, location: @agenda_item }
      else
        format.html { render :new }
        format.json { render json: @agenda_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agenda_items/1
  # PATCH/PUT /agenda_items/1.json
  def update
    respond_to do |format|
      if @agenda_item.update(agenda_item_params)
        format.html { redirect_to @agenda_item, notice: 'Agenda item was successfully updated.' }
        format.json { render :show, status: :ok, location: @agenda_item }
      else
        format.html { render :edit }
        format.json { render json: @agenda_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agenda_items/1
  # DELETE /agenda_items/1.json
  def destroy
    @agenda_item.destroy
    respond_to do |format|
      format.html { redirect_to agenda_items_url, notice: 'Agenda item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agenda_item
      @agenda_item = AgendaItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agenda_item_params
      params[:agenda_item]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController

	def index
		@meets = Meet.all
	end

	def new
		@meet = Meet.new
	end

	def create
		@meet = Meet.new params[:meet]
		if @meet.save
		  redirect_to :action => show, :id => @meet.id
		else
		  render :action => 'new'
		end
	end

	def destroy
		@meet = Meet.find params[:id]
		@meet.destroy
	end

	def edit
		@meet = Meet.find params[:id]
	end

	def update
		@meet = Meet.find params[:id]
		if @meet.update_attributes(params[:meet])
		  redirect_to :action => 'show', :id => @meet.id
		end
	end

private

	def 

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :description, :user_id, :start_time, :end_time,
                                   :invitees)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/agenda_items_helper.rb
module AgendaItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meeting_helper.rb
module MeetingHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/agenda_items/_form.html.erb
<%= simple_form_for(@agenda_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/agenda_items/edit.html.erb
<h1>Editing Agenda Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @agenda_item %> |
<%= link_to 'Back', agenda_items_path %>

app/views/agenda_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Agenda Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agenda_items.each do |agenda_item| %>
      <tr>
        <td><%= link_to 'Show', agenda_item %></td>
        <td><%= link_to 'Edit', edit_agenda_item_path(agenda_item) %></td>
        <td><%= link_to 'Destroy', agenda_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agenda item', new_agenda_item_path %>

app/views/agenda_items/new.html.erb
<h1>New Agenda Item</h1>

<%= render 'form' %>

<%= link_to 'Back', agenda_items_path %>

app/views/agenda_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_agenda_item_path(@agenda_item) %> |
<%= link_to 'Back', agenda_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meeting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="ui pointing menu">
  <a class="active item">
    <i class="home icon"></i> Home
  </a>
  <a class="item">
    <i class="mail icon"></i> Messages
  </a>
  <a class="item">
    <i class="user icon"></i> Friends
  </a>
  <div class="right menu">
    <div class="item">
      <div class="ui icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>
<% unless !user_signed_in? %>
    <div class="ui dropdown item">
      <%= current_user.email %>
      <i class="dropdown icon"></i>
      <div class="menu">
        <a class="item">Profile</a>
        <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "item" %>
      </div>
    </div>
<% end %>
  </div>
</div>

<%= yield %>

<script>
$('.ui.dropdown').dropdown();
</script>
<script>
$('.datepicker').pickadate();
</script>
</body>
</html>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |f| %>
  <%= f.input :title %> 
  <%= f.input_field :description, class: 'datepicker' %>
  <%= f.button :submit %>
<% end %>
<%= link_to 'Back', :action => nil %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="ui grid">
<p id="notice"><%= notice %></p>
<h1>Listing Rooms</h1>

<div class="eight wide column centered">
  <div class="ui segment">
  <div class="ui fluid category search">
    <div class="ui icon input">
      <input class="prompt" type="text" placeholder="Search rooms...">
      <i class="search icon"></i>
    </div>
    <div class="results"></div>
  </div>
</div>
</div>

</div>
<div class="ui page grid">

<% @rooms.each do |room| %>
    <div class="four wide column">
      <div class="ui card fluid">
        <div class="content">
          <a class="ui ribbon label red">Upcoming</a>
          <div class="header"><%= link_to room.title, room %></div>
          <div class="meta">Created <%=time_ago_in_words(room.created_at) %> ago</div>
          <div class="description">
          </div>
        </div>
      </div>
    </div>
<% end %>
<div class="four wide column">
<div class="ui card fluid">
  <div class="content">
    <div class="header">Create New Room</div>
        <%= link_to 'New Room ', new_room_path %><div class="ui icon button" data-content="Add users to your feed">
    <i class="add icon"></i>
  </div>
</div>
</div>

</div><!-- end of page grid -->

<script>
var
  content = [
    {
      title: 'Horse',
      description: 'An Animal',
    },
    {
      title: 'Cow',
      description: 'Another Animal',
    }
  ]
;
$('.ui.search')
  .search({
    source : content,
    searchFields   : [
      'title'
    ],
    searchFullText: false
  })
;
</script>



 

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>
<div class="ui page grid">
    <div class="ten wide column centered">
    	<div class="ui card fluid">
  <div class="content">
    <div class="header"><%= @room.title %></div>
    <div class="meta"><%= @room.created_at %></div>
    <div class="description">
      <%= @room.description %>
    </div>
  </div>
</div>
    </div>
  </div>




<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>